### PR TITLE
Update index.js.erb

### PR DESCRIPTION
**Pull request by sadfuzzy**
Power of Rails

### CODE REVIEW

**Comment by benwalks** [comment]
Nice addition, thanks.  I'll merge once I adjust the original articles to match :+1:

**Comment by sadfuzzy** [comment]
I've gone through articles - what is the best way to make PRs for editions, @benwalks?

**Comment by benwalks** [comment]
I don't have my articles in version control at the moment but there's absolutely no reason why I couldn't have them on my github.  

Nice idea mate, it'd be great to have the community help make them better.

**Comment by sadfuzzy** [comment]
Ok, great) Please, mention me, so I can see it in Github notifications or somehow :+1:

**Comment by benwalks** [comment]
Absolutely, thanks again.

**Comment by sadfuzzy** [comment]
By the way, articles are very nice and useful to get acquainted with social functions in Rails!

**Comment by benwalks** [comment]
Hey sadfuzzy, I have no idea why this sat in the PR's for so long, sorry.  The whole book is up in source control now, check out my Github profile :)

Thanks again for your help.

**Pull request merged**
